name: Builds
on:
  - pull_request
  - workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    name: Build 
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build with test flag
      run: |
        make TEST_FLAG=-DTESTING
        ls
    - run: |
        mkdir artifacts
    - uses: actions/upload-artifact@master
      with:
        name: build-artifacts
        path: | 
          *.so
          *.so.*


  cpu-test:
    name: CPU Test
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: build-artifacts
    - name: Run CPU tests
      run: |
        ./tests/CPU/cpu.sh
